spring:
  datasource:
      url: jdbc:mariadb://172.17.0.1:3306/grabit__prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
      driver-class-name: org.mariadb.jdbc.Driver
      username: lldjlocal
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: INFO
    com.ll.grabit: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
custom:
  site:
    baseUrl: https://test1.grabit.run
